# ==============================================================================
# Contenedor Relay ultraligero para Smee.io Client
# ==============================================================================
FROM node:20-alpine

RUN npm install --global smee-client

ENTRYPOINT ["smee"]
CMD ["--help"]
